In [7]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.tree import DecisionTreeClassifier
import numpy as np

data = []
labels = []

with open(r"C:/Users/wd/Documents/GitHub/MachineLearningStudy/data/lenses.txt") as ifile:
    for line in ifile:
        rowDict = {}
        tokens = line.strip().split('\t')
        rowDict['age'] = tokens[0]
        rowDict['prescript'] = tokens[1]
        rowDict['astigmatic'] = tokens[2]
        rowDict['tearRate'] = tokens[3]
        data.append(rowDict)
        labels.append(tokens[-1])

        
# 对应创建数据
# 一般来说 训练完成后 生成训练样本
x = np.array(data)
labels = np.array(labels)
y = np.zeros(labels.shape)
y[labels == 'hard'] = 1
y[labels == 'soft'] = 1
vec = DictVectorizer()
dx = vec.fit_transform(x).toarray()
print (dx)

# 调用sklearn的决策树 使用默认的参数 即CART
clf = DecisionTreeClassifier()
clf.fit(dx, y)

# 查看预测结果
from sklearn.metrics import classification_report
predictions = clf.predict(dx)
print (classification_report(y, predictions))

# 最后生成决策树
from sklearn import tree
tree.export_graphviz(clf, out_file='tree.dot')



[[0. 0. 1. 1. 0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0. 0. 1. 1. 0.]
 [0. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 1. 0. 1. 0. 1. 1. 0.]
 [0. 0. 1. 1. 0. 1. 0. 0. 1.]
 [0. 0. 1. 1. 0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 1. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1. 1. 0. 1. 0.]
 [1. 0. 0. 1. 0. 0. 1. 0. 1.]
 [1. 0. 0. 1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 0. 1. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1. 1. 0. 0. 1.]
 [1. 0. 0. 0. 1. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 0. 1. 0. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1. 1. 0. 0. 1.]
 [0. 1. 0. 0. 1. 1. 0. 1. 0.]]
             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00        15
        1.0       1.00      1.00      1.00         9

avg / total       1.00      1.00      1.00        24

