In [3]:
# coding:utf-8
from numpy import *


def file2matrix(filename):
    """
    Desc:
       导入训练数据
    parameters:
       filename: 数据文件路径
    return:
       数据矩阵 returnMat 和对应的类别
    备注:前3个标签为属性值 后面一个标签为类别标签
    """
    fr = open(filename)
    numberOfLines = len(fr.readlines())
    # 生成一个zero((2, 3))
    returnMat = zeros((numberOfLines, 3))
    classLabelVector = []
    #fr = open(filename)
    fr.close()
    fr = open(filename)
    index = 0
    for line in fr.readlines():
        line = line.strip()
        listFromLine = line.split('\t')
        # 每列的属性数据
        returnMat[index, :] = listFromLine[0:3]
        # 每列的类别数据,就是label标签
        classLabelVector.append(int(listFromLine[-1]))
        index += 1
    return returnMat, classLabelVector

In [12]:
# coding:utf-8
import numpy as np

def createDataSet():
    """
    desc:
      创建数据集
    parameters:
      无
    return:
      group - 数据集
      labels - 分类标签
    """
    group = np.array([[1, 101], [5, 89], [108, 5], [115, 8]])
    labels = ['love', 'love', 'action', 'action']
    return group, labels

group, labels = createDataSet()
print (group, labels)

[[  1 101]
 [  5  89]
 [108   5]
 [115   8]] ['love', 'love', 'action', 'action']


In [11]:
import datetime
import time
import calendar

def getMonthFirstDayAndLastDay(year=None, month=None, date_format='%Y-%m-%d'):
    """
    desc:
      获取某月的第一天和最后一天
    parameters:
      year - 年
      month - 月
      date_format - 转换的文件格式(默认%Y-%m-%d)
    return:
      firstDay, lastDay
    """
    if year:
        year = int(year)
    else:
        # 没有则获取当月的年
        year = datetime.date.today().year
    if month:
        month = int(month)
    else:
        month = datetime.date.today().month
    
    firstDayWeekDay, monthRange = calendar.monthrange(year, month)
    firstDay = datetime.date(year=year, month=month, day=1).strftime(date_format)
    lastDay = datetime.date(year=year, month=month, day=monthRange).strftime(date_format)
    return firstDay, lastDay
    

def getBetweenDays(begin_date, end_date, date_format):
    """
    desc:
     获取当月所有日期的列表
    parameters:
     begin_date -- 起始日期
     end_date   -- 截止日期
     date_format -- 时间格式
    return:
     返回指定日期范围的时间列表
    """
    date_list = []
    begin_date = datetime.datetime.strptime(begin_date, "%Y-%m-%d")
    end_date = datetime.datetime.strptime(end_date, "%Y-%m-%d")
    #begin_date = datetime.datetime.strptime(begin_date, "%Y-%m-%d")  
    #end_date = datetime.datetime
    #end_date = datetime.datetime.strptime(time.strftime('%Y-%m-%d',time.localtime(time.time())), "%Y-%m-%d")  
    while begin_date <= end_date:  
        date_str = begin_date.strftime(date_format)  
        date_list.append(date_str)  
        begin_date += datetime.timedelta(days=1)  
    return date_list 


firstDay, lastDay = getMonthFirstDayAndLastDay(2018, 6, '%Y-%m-%d')
print (getBetweenDays(firstDay, lastDay, "%y%m%d"))


['180601', '180602', '180603', '180604', '180605', '180606', '180607', '180608', '180609', '180610', '180611', '180612', '180613', '180614', '180615', '180616', '180617', '180618', '180619', '180620', '180621', '180622', '180623', '180624', '180625', '180626', '180627', '180628', '180629', '180630']


In [13]:
mat1, labelV = file2matrix(r"C:\Users\wd\Documents\GitHub\MachineLearning\input\2.KNN\datingTestSet2.txt")

print (mat1)

[[4.0920000e+04 8.3269760e+00 9.5395200e-01]
 [1.4488000e+04 7.1534690e+00 1.6739040e+00]
 [2.6052000e+04 1.4418710e+00 8.0512400e-01]
 ...
 [2.6575000e+04 1.0650102e+01 8.6662700e-01]
 [4.8111000e+04 9.1345280e+00 7.2804500e-01]
 [4.3757000e+04 7.8826010e+00 1.3324460e+00]]


import matplotlib
import matplotlib.pyplot as plt


datingDataMat, datingLabels = file2matrix(r"C:\Users\wd\Documents\GitHub\MachineLearning\input\2.KNN\datingTestSet2.txt")
fig = plt.figure()
ax = fig.add_subplot(111)
ax.scatter(datingDataMat[:, 0], datingDataMat[:, 1], 15.0*array(datingLabels), 15.0*array(datingLabels))
plt.show()

**归一化的定义**: 归一化就是要把需要处理的数据经过加工处理后 限制在你需要的一定范围内 首先归一化是为了后面的数据处理的方便 其次是保证程序运行时收敛加快 方法有如下:
1. 线性函数转换 y = (x - MinValue)/(MaxValue - MinValue)
2. 对数函数转换 y = log10(x) 以10为底数进行转换
3. 反余切函数转换 y = arctan(x)*2/PI
4. 式（1）将输入值换算为[-1,1]区间的值,在输出层用式2换算回初始值 归一化的具体作用是归纳 归一化在0-1之间的统计的概率分布

In [21]:
def autoNorm(dataSet):
    """
    Desc:
      归一化特征值,消除特征之间量级不同导致的影响
    parameter:
      dataSet:数据集
    return:
    
    归一化公式:
      Y = (x - Xmin)/(Xmax - Xmin)
      
    """
    minVals = dataSet.min(0)
    maxVals = dataSet.max(0)
    
    #极差
    ranges = maxVals - minVals
    normDataSet = zeros(shape(dataSet))
    m = dataSet.shape[0]
    normDataSet = dataSet - tile(minVals, (m, 1))
    normDataSet = normDataSet/tile(ranges, (m, 1))
    return normDataSet, ranges, minVals

In [16]:
from numpy import *
import operator

def classify0(inX, dataSet, labels, k):
    """
    desc:
      kNN算法
    parameters:
      inX - 用于分类的数据(测试集)
      dataSet - 用于训练的数据(训练集)
      labels - 分类标签
      k - KNN算法参数
    returns:
      sortedClassCount[0][0] - 分类结果
    """
    # 获取dataSet的行数
    dataSetSize = dataSet.shape[0]
    # 距离度量 
    diffMat = tile(inX, (dataSetSize, 1)) - dataSet
    # 二维特征相减后平凡
    sqDiffMat = diffMat ** 2
    # sum()所有元素相加 axis=0 列相加 axis=1 行相加
    sqDistances = sqDiffMat.sum(axis=1)
    # 所有行相加 
    distances = sqDistances ** 0.5
    
    #将距离排序 从小到大
    sortedDistIndicies = distances.argsort()
    #定义一个记录类别次数的字典
    classCount = {}
    for i in range(k):
        voteIlabel = labels[sortedDistIndicies[i]]
        classCount[voteIlabel]  = classCount.get(voteIlabel, 0) + 1
    #python3改成items()
    #key=operator.itemgetter(1) 根据字典的值进行排序
    #key=operator.itemgetter(0) 根据字典的键进行排序
    sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse=True)
    return sortedClassCount[0][0]

group, labels = createDataSet()
test = [101, 20]
knn_class = classify0(test, group, labels, 3)
print (knn_class)

action


In [23]:
def datingClassTest():
    """
    Desc:
    parameters:
    return:
    """
    # 取所有数据的0.1
    hoRatio = 0.1
    
    datingDataMat, datingLabels = file2matrix(r"C:\Users\wd\Documents\GitHub\MachineLearning\input\2.KNN\datingTestSet2.txt")
    # 归一化数据 返回归一化后的矩阵 数据范围和数据最小值
    normMat, ranges, minVals = autoNorm(datingDataMat)
                                              
    m = normMat.shape[0]
    numTestVecs = int(m * hoRatio)
    #print ("numTestVecs=", numTestVecs)
    errorCount = 0.0
    for i in range(numTestVecs):
       classifierResult = classify0(normMat[i,:], normMat[numTestVecs:m, :], datingLabels[numTestVecs:m], 4)
       print ("分类结果:%d\t 真实类别:%d"%(classifierResult, datingLabels[i]))
       if classifierResult != datingLabels[i]:
          errorCount += 1.0
    print ("错误率:%f%%"%((errorCount)/float(numTestVecs)*100))

if __name__ == "__main__":
    datingClassTest()

分类结果:3	 真实类别:3
分类结果:2	 真实类别:2
分类结果:1	 真实类别:1
分类结果:1	 真实类别:1
分类结果:1	 真实类别:1
分类结果:1	 真实类别:1
分类结果:3	 真实类别:3
分类结果:3	 真实类别:3
分类结果:1	 真实类别:1
分类结果:3	 真实类别:3
分类结果:1	 真实类别:1
分类结果:1	 真实类别:1
分类结果:2	 真实类别:2
分类结果:1	 真实类别:1
分类结果:1	 真实类别:1
分类结果:1	 真实类别:1
分类结果:1	 真实类别:1
分类结果:1	 真实类别:1
分类结果:2	 真实类别:2
分类结果:3	 真实类别:3
分类结果:2	 真实类别:2
分类结果:1	 真实类别:1
分类结果:2	 真实类别:2
分类结果:3	 真实类别:3
分类结果:2	 真实类别:2
分类结果:3	 真实类别:3
分类结果:2	 真实类别:2
分类结果:3	 真实类别:3
分类结果:2	 真实类别:2
分类结果:1	 真实类别:1
分类结果:3	 真实类别:3
分类结果:1	 真实类别:1
分类结果:3	 真实类别:3
分类结果:1	 真实类别:1
分类结果:2	 真实类别:2
分类结果:1	 真实类别:1
分类结果:1	 真实类别:1
分类结果:2	 真实类别:2
分类结果:3	 真实类别:3
分类结果:3	 真实类别:3
分类结果:1	 真实类别:1
分类结果:2	 真实类别:2
分类结果:3	 真实类别:3
分类结果:3	 真实类别:3
分类结果:3	 真实类别:3
分类结果:1	 真实类别:1
分类结果:1	 真实类别:1
分类结果:1	 真实类别:1
分类结果:1	 真实类别:1
分类结果:2	 真实类别:2
分类结果:2	 真实类别:2
分类结果:1	 真实类别:1
分类结果:3	 真实类别:3
分类结果:2	 真实类别:2
分类结果:2	 真实类别:2
分类结果:2	 真实类别:2
分类结果:2	 真实类别:2
分类结果:3	 真实类别:3
分类结果:1	 真实类别:1
分类结果:2	 真实类别:2
分类结果:1	 真实类别:1
分类结果:2	 真实类别:2
分类结果:2	 真实类别:2
分类结果:2	 真实类别:2
分类结果:2	 真实类别:2
分类结果:2	 真实类别:2
分类结果:3	 真实

构造一个能识别数字0-9的基于KNN分类器的手写数字识别系统

In [26]:
def img2vector(filename):
    returnVect = zeros((1, 1024))
    fr = open(filename)
    for i in range(32):
        lineStr = fr.readline()
        for j in range(32):
            returnVect[0, 32*i+j] = int(lineStr[j])
    return returnVect

In [27]:
testVector = img2vector(r"C:\Users\wd\Documents\GitHub\MachineLearning\input\2.KNN\trainingDigits\0_13.txt")
print (testVector)

[[0. 0. 0. ... 0. 0. 0.]]


In [ ]:
from os import listdir

def handwritingClassTest():
    hwLabels = []
    traingFileList = listdir(r"C:\Users\wd\Documents\GitHub\MachineLearning\input\2.KNN\trainingDigits")
    m = len(traingFileList)
    traingMat = zero((m, 1024))
    # hwLabels 存储0-9对应的index位置
    for i in range(m):
        fileNameStr = traingFileList[i]
        fileStr = fileNameStr.split('.')[0]
        classNumStr = int(fileStr.split('_')[0])
        hwLabels.append(classNumStr)
        # 将32*32的矩阵->1*1024的矩阵
        trainingMat[i, :] = img2vector(r"C:\Users\wd\Documents\GitHub\MachineLearning\input\2.KNN\trainingDigits\{}".format(fileNameStr))
    #导入测试数据
    testFileList = listdir(r'C:\Users\wd\Documents\GitHub\MachineLearning\input\2.KNN\testDigits')
    errorCount = 0.0
    mTest = len(testFileList)
    for i in range(mTest):
          fileNameStr = testFileList[i]
          fileStr = fileNameStr.split('.')[0]
          classNumStr = int(fileStr.split('_')[0])
          vectorUnderTest = img2vector(r'C:\Users\wd\Documents\GitHub\MachineLearning\input\2.KNN\testDigits\%s'%fileNameStr)
          classifierResult = classify0(vectorUndeTest, traingMat, hwLabels, 3)
          print ("the classifier came back with :%d, the real answer is: %d"%(classiferResult, classNumStr))
          if (classifierResult != classNumStr): errorCount += 1.0
    print ("\nthe total number of errors is :%d\n"%errorCount)
    print ("\nthe total error rate is :%f\n"%(errorCount/float(mTest)))

In [7]:
# coding:utf-8
# 使用鸢尾花数据集进行测试
from sklearn import neighbors
from sklearn.datasets import load_iris
import sklearn
import numpy as np

# 查看iris数据集
iris = load_iris()
#print (iris)
mat1, labelV = file2matrix(r"C:\Users\wd\Documents\GitHub\MachineLearning\input\2.KNN\datingTestSet2.txt")
knn = neighbors.KNeighborsClassifier()
# 训练数据集
knn.fit(mat1, labelV)
#knn.fit(iris.data, iris.target)
# 预测
#predict = knn.predict([[0.1, 0.2, 0.3, 0.4]])
# 阵列
predict = knn.predict([[80920, 12.326976, 0.953952]])
print (predict)
#print (iris.target_names[predict])

[1]
